



export const movies = [
    { id:252171, title:"A Girl Walks Home Alone at Night", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:447332, title:"A Quiet Place", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:520763, title:"A Quiet Place Part II", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:73, title:"American History X", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:396806, title:"Anon", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:329865, title:"Arrival", seen:true, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:18785, title:"Baksmällan", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:271404, title:"Beyond Skyline", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:569547, title:"Black Mirror: Bandersnatch", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:257117, title:"Blood Punch", seen:true, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:513310, title:"Boss Level", seen:false, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:425972, title:"Cargo", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:801335, title:"Carter", seen:false, vote:0, saved:true, lists:['Saved', 'Korea'] },
    { id:76726, title:"Chronicle", seen:false, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:354912, title:"Coco", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:461130, title:"Code 8", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:220289, title:"Coherence", seen:true, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:11655, title:"Cronos", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:475961, title:"Curvature", seen:false, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:924, title:"Dawn of the Dead", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:923, title:"Dawn of the Dead", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:293660, title:"Deadpool", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:497, title:"Den gröna milen", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:44040, title:"Devil", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:43920, title:"Dog Pound", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:646380, title:"Don't Look Up", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:520901, title:"Doom: Annihilation", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:568124, title:"Encanto", seen:true, vote:0, saved:true, lists:['Saved', 'Family'] },
    { id:522681, title:"Escape Room", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:29917, title:"Exam", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:568091, title:"Fractured", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:550988, title:"Free Guy", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:453405, title:"Gemini Man", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:801335, title:"Girl in the Basement", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:450465, title:"Glass", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:440021, title:"Happy Death Day", seen:true, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:512196, title:"Happy Death Day 2U", seen:false, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:376865, title:"High Life", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:254302, title:"High-Rise", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:575774, title:"His House", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:475210, title:"How It Ends", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:49530, title:"In Time", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:581726, title:"Infinite", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:797861, title:"Infinitum: Subject Unknown", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:5595, title:"La Habitación de Fermat", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:37933, title:"Legender från Övärlden", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:783461, title:"Looop Lapeta", seen:false, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:590223, title:"Love and Monsters", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:508943, title:"Luca", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:769, title:"Maffiabröder", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:521936, title:"Mega Time Squad", seen:true, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:675054, title:"MexZombies", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:458576, title:"Monster Hunter", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:597208, title:"Nightmare Alley", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:278, title:"Nyckeln till frihet", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:762504, title:"Nope", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:466272, title:"Once Upon a Time… in Hollywood", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:513434, title:"One Cut of the Dead", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:775996, title:"Outside the Wire", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:19898, title:"Pandorum", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:496243, title:"Parasit", seen:true, vote:0, saved:true, lists:['Saved', 'Korea'] },
    { id: 635731, title:"Pig", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:12429, title:"Ponyo på klippan vid havet", seen:true, vote:0, saved:true, lists:['Saved', 'Ghibli'] },
    { id:605116, title:"Project Power", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:1576, title:"Resident Evil", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:313943, title:"Revolt", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:653569, title:"Save Yourselves!", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:214, title:"Saw III", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:424, title:"Schindler's List", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:273477, title:"Scouts Guide to the Zombie Apocalypse", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:55165, title:"Simple Simon", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:50123, title:"Skins", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:11466, title:"Slim Susie", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:581389, title:"Space Sweepers", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:129, title:"Spirited Away", seen:true, vote:0, saved:true, lists:['Saved', 'Ghibli'] },
    { id:594718, title:"Sputnik", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:169644, title:"Stalled", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:559581, title:"Stowaway", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:549294, title:"Synchronic", seen:false, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:577922, title:"Tenet", seen:true, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:696806, title:"The Adam Project", seen:true, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:22970, title:"The Cabin in the Woods", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:376134, title:"The Discovery", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:442249, title:"The First Purge", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:602223, title:"The Forever Purge", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:425552, title:"The Lure", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:333484, title:"The Magnificent Seven", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:198663, title:"The Maze Runner", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:242090, title:"The One I Love", seen:false, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:158015, title:"The Purge", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:316727, title:"The Purge: Election Year", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:180299, title:"The Raid: Retaliation", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:11152, title:"The Ruins", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:242095, title:"The Signal", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:588228, title:"The Tomorrow War", seen:false, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:293670, title:"The Wailing", seen:false, vote:0, saved:true, lists:['Saved', 'Korea'] },
    { id:535167, title:"The Wandering Earth", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:14139, title:"Timecrimes", seen:true, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:26466, title:"Triangle", seen:true, vote:4, saved:true, lists:['Saved', 'Time'] },
    { id:366171, title:"To Your Last Death", seen:false, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:496704, title:"Tremors: A Cold Day in Hell", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:529216, title:"Under stormen", seen:false, vote:0, saved:true, lists:['Saved', 'Time'] },
    { id:500664, title:"Upgrade", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:643586, title:"Willy's Wonderland", seen:false, vote:0, saved:true, lists:['Saved'] },
    { id:72190, title:"World War Z", seen:true, vote:0, saved:true, lists:['Saved'] },
    { id:437311, title:"Órbita 9", seen:false, vote:0, saved:true, lists:['Saved'] },

]

export const genres = [
    { id: 28, name: "Action", active:false },
    { id: 12, name: "Äventyr", active:false },
    { id: 16, name: "Animerat", active:false },
    { id: 35, name: "Komedi", active:false },
    { id: 80, name: "Kriminal", active:false },
    { id: 99, name: "Dokumentär", active:false },
    { id: 18, name: "Drama", active:false },
    { id: 10751, name: "Familj", active:false },
    { id: 14, name: "Fantasy", active:false },
    { id: 36, name: "Historisk", active:false },
    { id: 27, name: "Skräck", active:false },
    { id: 10402, name: "Music", active:false },
    { id: 9648, name: "Mystik", active:false },
    { id: 10749, name: "Romantik", active:false },
    { id: 878, name: "Science Fiction", active:false },
    { id: 10770, name: "TV-film", active:false },
    { id: 53, name: "Thriller", active:false },
    { id: 10752, name: "Krig", active:false },
    { id: 37, name: "Västern", active:false }

]


export const keywords = [
    { id: 502, name: 'ambush' },
    { id: 567, name: 'alcohol' },
    { id: 1366, name: 'shotgun' },
    { id: 4262, name: 'tea' },
    { id: 4523, name: 'joint' },
    { id: 7149, name: 'machismo' },
    { id: 9227, name: 'cocktail' },
    { id: 9897, name: 'rifle' },
    { id: 10776, name: 'marijuana' },
    { id: 11488, name: 'pot smoking' },
    { id: 15394, name: 'hatchet' },
    { id: 15395, name: 'antique' },
    { id: 15396, name: 'cardsharp' },
    { id: 18047, name: 'anger' },
    { id: 34117, name: 'cult film' },
    { id: 167542, name: 'carjacking' },
    { id: 207592, name: 'piano' },
    { id: 227944, name: 'strip show' },
    { id: 227945, name: 'high stakes' },
    { id:818, name:"based on novel or book"},
    { id:825, name:"support group"},
    { id:851, name:"dual identity"},
    { id:1541, name:"nihilism"},
    { id:1721, name:"fight"},
    { id:3927, name:"rage and hate"},
    { id:4142, name:"insomnia"},
    { id:4565, name:"dystopia"},
    { id:9181, name:"alter ego"},
    { id:11687, name:"breaking the fourth wall"},
    { id:34117, name:"cult film"},
    { id:156761, name:"split personality"},
    { id:179173, name:"quitting a job"},
    { id:212803, name:"dissociative identity disorder"},
    { id:260426, name:"self destructiveness"}

]